//
// Created by Tooster on 26.01.2018.
//

#ifndef SHOGI_UTILS_H
#define SHOGI_UTILS_H


/// enum for pawns

#define     SHOGI_SCALE_FACTOR              0.7
#define     SHOGI_BOARD_SIZE                9
#define     SHOGI_PAWN_IS_BLACK(pawn) ((pawn)%2 == 1)

#define     SHOGI_PAWN_TYPE_COUNT           8
enum SHOGI_PAWN {
    SHOGI_PAWN_K,
    SHOGI_PAWN_G,
    SHOGI_PAWN_S,
    SHOGI_PAWN_N,
    SHOGI_PAWN_L,
    SHOGI_PAWN_B,
    SHOGI_PAWN_R,
    SHOGI_PAWN_P
};

#define     SHOGI_PAWN_DETAILED_TYPE_COUNT  28
enum SHOGI_PAWN_DETAILED {
    SHOGI_PAWN_K_WHITE,
    SHOGI_PAWN_K_BLACK,

    SHOGI_PAWN_G_WHITE,
    SHOGI_PAWN_G_BLACK,

    SHOGI_PAWN_S_WHITE,
    SHOGI_PAWN_S_BLACK,
    SHOGI_PAWN_S_PRO_WHITE,
    SHOGI_PAWN_S_PRO_BLACK,

    SHOGI_PAWN_N_WHITE,
    SHOGI_PAWN_N_BLACK,
    SHOGI_PAWN_N_PRO_WHITE,
    SHOGI_PAWN_N_PRO_BLACK,

    SHOGI_PAWN_L_WHITE,
    SHOGI_PAWN_L_BLACK,
    SHOGI_PAWN_L_PRO_WHITE,
    SHOGI_PAWN_L_PRO_BLACK,

    SHOGI_PAWN_B_WHITE,
    SHOGI_PAWN_B_BLACK,
    SHOGI_PAWN_B_PRO_WHITE,
    SHOGI_PAWN_B_PRO_BLACK,

    SHOGI_PAWN_R_WHITE,
    SHOGI_PAWN_R_BLACK,
    SHOGI_PAWN_R_PRO_WHITE,
    SHOGI_PAWN_R_PRO_BLACK,

    SHOGI_PAWN_P_WHITE,
    SHOGI_PAWN_P_BLACK,
    SHOGI_PAWN_P_PRO_WHITE,
    SHOGI_PAWN_P_PRO_BLACK
};

#endif //SHOGI_UTILS_H
